### ISSUE TITLE
Creating an animated SVG for the website

### ISSUE THREAD

**Issue by adilshehzad786** [CNCF-Lahore/EKS-Workshop#2]
Hey Moeez here is a sample, we need for EKS workshop website. 
Your ticket is linked to this : https://github.com/CNCF-Lahore/EKS-Workshop/issues/1

![Image](https://github.com/CNCF-Lahore/EKS-Workshop/assets/53600644/5ec9bbd1-e278-4b5b-b0a0-ccf844878749)

**Comment by adilshehzad786** [comment]
Any update?

**Comment by adilshehzad786** [comment]
@moezmustafa  can you please work on it

**Comment by adilshehzad786** [comment]
Taking this task from @moezmustafa

**Comment by moezmustafa** [comment]
Link to the final animation : 
https://www.canva.com/design/DAGDuyBAfDA/amkXPTQ3uhQXeZngxgWxrw/edit

**Comment by moezmustafa** [comment]
@muhammadbilal10 use this animation for the header , of aws eks
